language: php

php:
    - 7.3
    - 7.4
    - 8.0
    - nightly

env:
    global:
        - secure: "RXRr93fTs89A7D/BvK5s2SnnvdsGgedjHBBfQjzChP3J/sgVQ0sAK9krqJ3HL45dR2nCxJ7JKJRdwWVB2ZurihzAoCXt5c/R8D5MdlW56KaI7fPLhyXSV9vm4c3NMRYS22gXbPWjK6y41tNMSeyIarjYROBMJXf8oC67E7QVivw="
        - GH_REPO: github.com/locomotivemtl/charcoal-project-boilerplate.git

matrix:
    allow_failures:
        - php: nightly

before_script:
    ## Init composer
    - composer selfupdate --quiet
    - composer install -n

    ## Create temporary folders
    - mkdir -p build/logs\

script:
    - composer test

after_script:
    - php vendor/bin/coveralls -v
    - bash build/travis/phpdoc_ghpages.sh
    - bash build/travis/apigen_ghpages.sh

notifications:
    slack: locomotivemtl:d9h8ZWwTZ6b3WUsSP9s26nb1
    email: charcoal@locomotive.ca
